# Generated by Django 5.1.4 on 2024-12-16 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conservation',
            name='status',
            field=models.CharField(choices=[('PLANNED', 'Direncanakan'), ('ONGOING', 'Sedang Berjalan'), ('COMPLETED', 'Selesai'), ('CANCELLED', 'Dibatalkan')], default='PLANNED', max_length=20),
        ),
    ]
