# Generated by Django 5.1.4 on 2024-12-16 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_conservation_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conservation',
            name='status',
            field=models.CharField(max_length=100),
        ),
    ]
